var elements =   [ 
    {
    id: 0 ,
    title: "Breaking Bad",
    poster: "css/bad.jpg",  
    description: "Un profesor de Química de secundaria con cáncer terminal se asocia a un exestudiante para asegurar el futuro de su familia al fabricar y vender metanfetamina.", 
    cast: "Bryan Cranston, Aaron Paul, Anna Gunn", 
    gender: "Drama",
    score:"3/5",
    },
{
    id: 1 ,
    title:"Narcos",
    poster:"css/narcos.jpg",
    description:"La verdadera historia de los poderosos y violentos cárteles de droga colombianos es el marco de esta serie dramática sobre el narco.",
    cast:"Wagner Moura, Pedro Pascal, Boyd Holbrook",
    gender:"Drama",
    score:"2/5",
},
{
    id: 2 ,
    title:"Stranger Things",
    poster:"css/things.jpg",
    description:"Después de la extraña desaparición de un niño, un pueblo se encuentra ante un misterio que revela experimentos secretos, fuerzas sobrenaturales y a una niña muy especial.",
    cast:"Winona Ryder, David Harbour, Finn Wolfhard",
    gender:"Ciencia ficción",
    score:"4/5",
},
{
    id: 3 ,
    title:"Black Mirror",
    poster:"css/black.jpg",
    description:"Antología de ciencia ficción dominada por el extrañamiento y la inminencia del futuro, donde la tecnología más avanzada choca contra los instintos más oscuros.",
    cast:"Jesse Plemons, Cristin Milioti, Jimmi Simpson",
    gender:"Ciencia ficción",
    score:"3/5",
},
{
    id: 4 , 
    title:"House of Cards",
    poster:"css/house.jpg",
    description:"Un despiadado político no se detendrá ante nada en su afán por conquistar Washington D. C.",
    cast:"Robin Wright, Michael Kelly, Diane Lane",
    gender:"Drama político",
    score:"2/5",
},
{
    id: 5,
    title:"Daredevil",
    poster:"css/devil.jpg",
    description:"Matt Murdock quedó ciego tras un accidente de niño, pero ahora con sus cuatro sentidos incrementados se dedica a luchar contra la injusticia como abogado y superhéroe.",
    cast:"Charlie Cox, Deborah Ann Woll, Elden Henson",
    gender:"Acción",
    score:"2/5",
}
] 